#!/bin/sh

module="char_device_pipe"
major_device="char_device"
child_device="char_pipe"
mode="777"

sudo /sbin/insmod $module.ko $* || exit 1
major=$(awk "\$2==\"$major_device\" {print \$1}" /proc/device
	
sudo rm -f /dev/$major_device
sudo rm -f /dev/$child_device
sudo mknod -m $mode /dev/$major_device c $major 0
sudo mknod -m $mode /dev/$child_device c $major 1