#!/bin/sh

module="char_device"
device="char_device"
mode="777"


sudo /sbin/insmod $module.ko $* || exit 1
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
sudo rm -f /dev/$device
sudo mknod -m $mode /dev/$device c $major 0
