#!/bin/sh

module="test_timer"
device="test_timer"
mode="777"


sudo /sbin/insmod $module.ko $* || exit 1
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
sudo rm -f /dev/$device
#sudo mknod -m $mode /dev/$device c $major 0
