#!/bin/sh

module="char_pipe"
major_device="char_pipe"
mode="777"

sudo /sbin/insmod $module.ko $* || exit 1
major=$(awk "\$2==\"$major_device\" {print \$1}" /proc/devices)

sudo rm -f /dev/$major_device
sudo mknod -m $mode /dev/$major_device c $major 0
